fichier <- read.csv(file = "household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
powerconsumption <- subset(fichier, fichier$Date=="1/2/2007" | fichier$Date=="2/2/2007")
with(powerconsumption, plot(as.POSIXct(paste(powerconsumption$Date, powerconsumption$Time), format="%d/%m/%Y %H:%M:%S"), Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering"))
with(powerconsumption, lines(as.POSIXct(paste(powerconsumption$Date, powerconsumption$Time), format="%d/%m/%Y %H:%M:%S"), Sub_metering_2, type = "l", col = "red"))
with(powerconsumption, lines(as.POSIXct(paste(powerconsumption$Date, powerconsumption$Time), format="%d/%m/%Y %H:%M:%S"), Sub_metering_3, type = "l", col = "blue"))
legend("topright", lty = 1, col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "~/Documents/01_Knowledge/01_Coursera/Exploratory_Data_Analysis/Week1/Plot3.png", width = 480, height = 480, units = "px")
dev.off()